# https://travis-ci.org/candango/firenado
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-redis.txt"
  - "pip install -r requirements-sqlalchemy.txt"
  - "pip install -r requirements-test.txt"
script:
  - "nosetests firenado.test.conf"
  - "nosetests firenado.test.service"
  - "nosetests firenado.test.tornadoweb"
  - "nosetests firenado.test.util.file"
